###############################################################################
#
#                              FULLY KIOSK BROWSER
#
###############################################################################
#------------------------------------------------------------------------------
sensor:
  - platform: rest
    name: foo
    json_attributes:
      - batteryLevel
      - kioskMode
      - screenBrightness
      - motionDetectorState
      - maintenanceMode
      - appFreeMemory
      - appUsedMemory
      - totalFreeMemory
      - totalUsedMemory
      - hostname4
      - ip4
      - mac
      - locationLatitude
      - locationLongitude
      - locationAltitude
      - startUrl
      - currentPage
    resource: !secret foo_rest
    value_template: '{{ value_json.isScreenOn }}'
  - platform: template
    sensors:
      foo_battery_level:
        friendly_name: "foo_battery_level"
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.foo.attributes.batteryLevel }}"
switch:
- platform: command_line
  switches:
    foo_screen:
      command_on: !secret foo_screen_on
      command_off: !secret foo_screen_off
      command_state: !secret foo_screen_state
      value_template: '{{ value == "on" }}'
      friendly_name: Foo Screen
