###############################################################################
#
#                 MUSIC IN THE BATHROOM WHEN THE LIGHT COMES UP
#
###############################################################################
#------------------------------------------------------------------------------
scene:
#------------------------------------------------------------------------------
  - name: Radio Successiva
    entities:
      script.radio_successiva_con_dash_button: on
  - name: Spegni Musica 
    entities:
      script.arresta_musica_con_dash_button: on
#------------------------------------------------------------------------------
input_number:
#------------------------------------------------------------------------------
  numero_radio:
    name: numero_radio
    min: 1
    max: 5
    step: 1
    initial: 1
  volume_radio_bagno:
    name: Volume Radio bagno
    min: 0
    max: 10
    step: 1
    initial: 6
#------------------------------------------------------------------------------
input_boolean:
#------------------------------------------------------------------------------
  volume_radio_mute_bagno:
    name: Mute
    initial: off
    icon: mdi:volume-mute
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
- platform: template
  sensors:
    volume_chromecast_bagno:
      value_template: >
        {% if is_state('media_player.batchroom', 'on')  %}
          {{ states.media_player.kitchen.attributes.volume_level }}
        {% else %}
          0
        {% endif %}
- platform: template
  sensors:
    luce_accesa_bagno:
      friendly_name: "Luce Accesa Bagno"
      value_template: >
        {% if states('sensor.sensore_light') | float > 0 %}
          Accesa
        {% else %}
          Spenta
        {% endif %}
#------------------------------------------------------------------------------
switch:
#------------------------------------------------------------------------------
  - platform: template
    switches:
      volume_radio_mute_bagno:
        friendly_name: volume radio mute bagno
        value_template: "{{ is_state('input_boolean.volume_radio_mute_bagno', 'on') }}"
        turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.volume_radio_mute_bagno
        - service: media_player.volume_mute
          data_template:
            entity_id: media_player.kitchen
            is_volume_muted: True
        turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.volume_radio_mute_bagno
        - service: media_player.volume_mute
          data_template:
            entity_id: media_player.kitchen
            is_volume_muted: False
#------------------------------------------------------------------------------
script:
#------------------------------------------------------------------------------
  arresta_musica_con_dash_button:
    alias: Arresta Musica con Dash Button
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.bathroom
      - service: input_number.set_value
        data_template:
          entity_id: input_number.numero_radio
          value: '1.0'
#******************************************************************************
  radio_successiva_con_dash_button:
    alias: Radio Successiva con Dash Button
    sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.bathroom
        media_content_id: >
          {% if is_state("input_number.numero_radio", "1.0") %}
            http://mp3channels.webradio.antenne.de/workout-hits.aac
          {%-elif is_state("input_number.numero_radio", "2.0") %}
            http://radiostream.flaixfm.cat:8002/;stream.nsv
          {%-elif is_state("input_number.numero_radio", "3.0") %}
            http://streaming.novaentertainment.com.au/nova100
          {%-elif is_state("input_number.numero_radio", "4.0") %}
            http://streaming.novaentertainment.com.au/smooth915 
          {%-elif is_state("input_number.numero_radio", "5.0") %}
            http://shoutcast.sbs.com.au/SBSChill
          {% else %}
            "None"
          {% endif %}
        media_content_type: 'audio/mp4'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.numero_radio
        value: '{{ states.input_number.numero_radio.state | int + 1.0 }}'
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
#  - alias: Lancia musica se viene accesa la luce
#    trigger:
#    - platform: state
#      entity_id: sensor.luce_accesa_bagno
#      to: Accesa
#    condition:
#      condition: and
#      conditions:
#        - condition: time
#          after: '18:00:00'
#        - condition: time
#          before: '23:30:00'
#    action:
#    - service: media_player.play_media
#      data:
#        entity_id: media_player.bathroom
#        media_content_id: http://mp3channels.webradio.antenne.de/workout-hits.aac
#        media_content_type: 'audio/mp4'
#    - service: input_number.set_value
#      data_template:
#        entity_id: input_number.numero_radio
#        value: '2.0'
#******************************************************************************
#  - alias: Ferma musica se viene spenta la luce
#    trigger:
#    - platform: state
#      entity_id: sensor.luce_accesa_bagno
#      to: Spenta
#    action:
#    - service: media_player.turn_off
#      data:
#        entity_id: media_player.bathroom
#    - service: input_number.set_value
#      data_template:
#        entity_id: input_number.numero_radio
#        value: '1.0'
#******************************************************************************
  - alias: Resetta numero radio
    trigger:
    - platform: state
      entity_id: input_number.numero_radio
      to: "6.0"
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.numero_radio
        value: '1.0'
#******************************************************************************