###############################################################################
#
#                                 RF SENSORS
#
###############################################################################
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
  - platform: mqtt
    state_topic: "sensors/rf/receiver"
    name: "RF Receiver"
  - platform: mqtt
    state_topic: "sensors/us/receiver"
    name: "US Receiver"
  - platform: mqtt
    state_topic: "sensors/rf/receiver2"
    name: "RF Receiver 2"
  - platform: mqtt
    state_topic: "sensors/wifi/receiver"
    name: "Wifi Pir Sensor"
#------------------------------------------------------------------------------
binary_sensor:
#------------------------------------------------------------------------------
#******************************   LETTO   *************************************
  - platform: template
    sensors:
      motion_sensor_rf_1:
        friendly_name: "Motion Sensor RF 1"
        device_class: motion
        delay_off:
          seconds: 20
        value_template: >-
          {{ is_state('sensor.rf_receiver', '13679406') }}

  - platform: template
    sensors:
      motion_sensor_rf_6:
        friendly_name: "Motion Sensor RF 6"
        device_class: motion
        delay_off:
          seconds: 20
        value_template: >-
          {{ is_state('sensor.rf_receiver', '1847644') }}
 
#****************************   CORRIDOIO  *************************************
  - platform: template
    sensors:
      motion_sensor_rf_2:
        friendly_name: "Motion Sensor RF 2"
        device_class: motion
        delay_off:
          seconds: 240
        value_template: >-
          {{ is_state('sensor.rf_receiver', '1118556') }}
#*******************************   BAGNO   ************************************
  - platform: template
    sensors:
      motion_sensor_rf_3:
        friendly_name: "Motion Sensor RF 3"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.rf_receiver', '1855836') }}
#******************************* CUCINA 2 *************************************
  - platform: template
    sensors:
      motion_sensor_rf_4:
        friendly_name: "Motion Sensor RF 4"
        device_class: motion
        delay_off:
          seconds: 120
        value_template: >-
          {{ is_state('sensor.rf_receiver', '7815516') }}
#***************************** Bagno Uscita ***********************************
  - platform: template
    sensors:
      motion_sensor_rf_5:
        friendly_name: "Motion Sensor RF 5"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.rf_receiver', '12916060') }}
#************************* Telecomando Luci Posizione D************************
  - platform: template
    sensors:
# luci salotto spente
      telecomando_rf_1d_off:
        friendly_name: "Telecomando RF 1D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5755907') }}
# luci salotto accese
      telecomando_rf_1d_on:
        friendly_name: "Telecomando RF 1D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5755916') }}
# blu
      telecomando_rf_2d_off:
        friendly_name: "Telecomando RF 2D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5731331') }}
# modalità film
      telecomando_rf_2d_on:
        friendly_name: "Telecomando RF 2D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5731340') }}
# arancio
      telecomando_rf_3d_off:
        friendly_name: "Telecomando RF 3D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5725187') }}
# azzurro
      telecomando_rf_3d_on:
        friendly_name: "Telecomando RF 3D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5725196') }}
#****************** Telecomando Bianco Luci Posizione IV***********************
  - platform: template
    sensors:
# luci salotto spente
      telecomando_rf_1iv_off:
        friendly_name: "Telecomando RF 1IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2326706688') }}
# luci salotto accese
      telecomando_rf_1iv_on:
        friendly_name: "Telecomando RF 1IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2192488960') }}
# blu
      telecomando_rf_2iv_off:
        friendly_name: "Telecomando RF 2IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2729359872') }}
# modalità film
      telecomando_rf_2iv_on:
        friendly_name: "Telecomando RF 2IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2897132032') }}
# arancio
      telecomando_rf_3iv_off:
        friendly_name: "Telecomando RF 3IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2460924416') }}
# azzurro
      telecomando_rf_3iv_on:
        friendly_name: "Telecomando RF 3IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2628696576') }}
# arancio
      telecomando_rf_4iv_off:
        friendly_name: "Telecomando RF 4IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2746137088') }}
# azzurro
      telecomando_rf_4iv_on:
        friendly_name: "Telecomando RF 4IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2477701632') }}
#Isnatch IV