###############################################################################
#
#                                 BATHROOM THERMOSTAT 
#
###############################################################################
#------------------------------------------------------------------------------
timer:
#------------------------------------------------------------------------------
  termostato_bagno:
    duration: '00:30:00'
#------------------------------------------------------------------------------
group:
#------------------------------------------------------------------------------
  termostato_bagno:
    name: Termostato Bagno
    control: hidden
    entities:
      - input_boolean.termostato_bagno_interruttore
      - climate.termostato_bagno
      - input_number.termostato_bagno_target_temp
      - sensor.termostato_bagno_ac_target
      - input_boolean.termostato_bagno_timer_interruttore
      - input_number.termostato_bagno_timer
      - sensor.termostato_bagno_tempo_impostato
      - sensor.countdown_bagno
      - switch.bagno_scalda
      - input_boolean.visualizza_telecomando_termoventilatore
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
  - platform: template
    sensors:
      temperatura_corretta_bagno_per_termostato:
        friendly_name: "Temperatura Bagno"
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.sensore_temperature')|float - 0.2 }}"
#******************************************************************************
  - platform: template
    sensors:
      tempo_spegnimento_bagno:
        value_template: "{{ ( ( states.input_number.termostato_bagno_timer.state | int) * 60 ) | int }}"
#******************************************************************************
# Termostato Bagno
  - platform: template
    sensors:
      termostato_bagno_ac_target:
        friendly_name: 'Temperatura Impostata'
        value_template: '{{ states.input_number.termostato_bagno_target_temp.state | int }}'
        unit_of_measurement: '°C'
      termostato_bagno_tempo_impostato:
        friendly_name: 'Tempo Impostato'
        value_template: '{{ states.input_number.termostato_bagno_timer.state | int }}'
        unit_of_measurement: 'min'
#******************************************************************************
  - platform: template
    sensors:
      countdown_bagno:
        friendly_name: "Tempo Rimanente"
        value_template: "{{ states('sensor.countdown_bagno_hours') }} : {{ states('sensor.countdown_bagno_minutes') }} : {{ states('sensor.countdown_bagno_seconds') }}"
  - platform: template
    sensors:
      countdown_bagno_hours:
        value_template: >
          {% if ( ( states('input_number.countdown_bagno') | float / 3600 ) | int ) < 10 %}
            0{{( states('input_number.countdown_bagno') | float / 3600 ) | int}}
          {% else %}
            {{( states('input_number.countdown_bagno') | float / 3600 ) | int}}
          {% endif %}
  - platform: template
    sensors:
      countdown_bagno_minutes:
        value_template: >
          {% if ( ((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) | int ) < 10 %}
            0{{((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) | int}}
          {% else %}
            {{((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) | int}}
          {% endif %}
  - platform: template
    sensors:
      countdown_bagno_seconds:
        value_template: >
          {% if ( ((((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) - ( states('sensor.countdown_bagno_minutes') | float )) * 60 ) | int ) < 10 %}
            0{{((((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) - ( states('sensor.countdown_bagno_minutes') | float )) * 60 ) | int}}
          {% else %}
            {{((((( states('input_number.countdown_bagno') | float / 3600 ) - ( states('sensor.countdown_bagno_hours') | float )) * 60 ) - ( states('sensor.countdown_bagno_minutes') | float )) * 60 ) | int}}
          {% endif %}
  - platform: template
    sensors:
      countdown_bagno_meno_1:
        value_template: "{{( states('input_number.countdown_bagno') | int - 1 ) | int}}"
#------------------------------------------------------------------------------
switch:
#------------------------------------------------------------------------------
  - platform: broadlink
    host: !secret broadlink_rm_mini
    mac: !secret mac_broadlink_rm_mini
    timeout: 15
    type: rm_mini
    switches:
      bagno_scalda:
        command_on: 'JgBQAAABKpUSExIUEhQRFBEUEhMSFBEVETgSNxI4EjgSOBE4EjgSOBI4ERQSFRAUExISExIUExISExI4EjgSOBE4EjgSOBI3EgAFIwABK0kSAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABKpUSExIUEhQRFBEUEhMSFBEVETgSNxI4EjgSOBE4EjgSOBI4ERQSFRAUExISExIUExISExI4EjgSOBE4EjgSOBI3EgAFIwABK0kSAA0FAAAAAAAAAAA='
#******************************************************************************
  - platform: template
    switches:
      accendi_termostato_dashboard_bagno:
        value_template: "{{ is_state('input_boolean.termostato_bagno_interruttore', 'on') }}"
        turn_on:
          - service: homeassistant.turn_on
            data:
              entity_id: input_boolean.termostato_bagno_interruttore
          - service: homeassistant.turn_on
            data:
              entity_id: input_boolean.termostato_bagno_timer_interruttore
        turn_off:
          - service: homeassistant.turn_off
            data:
              entity_id: input_boolean.termostato_bagno_interruttore
          - service: homeassistant.turn_off
            data:
              entity_id: input_boolean.termostato_bagno_timer_interruttore
#******************************************************************************
      spegni_timer_dashboard_bagno:
        value_template: "{{ is_state('input_boolean.termostato_bagno_timer_interruttore', 'on') }}"
        turn_on:
          - service: homeassistant.turn_on
            data:
              entity_id: input_boolean.termostato_bagno_timer_interruttore
        turn_off:
          - service: homeassistant.turn_off
            data:
              entity_id: input_boolean.termostato_bagno_timer_interruttore
#------------------------------------------------------------------------------
climate:
#------------------------------------------------------------------------------
  - platform: generic_thermostat
    name: Termostato Bagno
    heater: switch.bagno_scalda
    target_sensor: sensor.sensore_temperature
    min_temp: 16
    max_temp: 30
#    target_temp: 24
    tolerance: 0.3
    min_cycle_duration:
      seconds: 5
#------------------------------------------------------------------------------
input_number:
#------------------------------------------------------------------------------
  termostato_bagno_target_temp:
    name: Imposta Temp
    min: 16
    max: 30
    step: 1
    initial: 30
#******************************************************************************
  termostato_bagno_timer:
    name: Tempo
    min: 0
    max: 120
    step: 1
    initial: 30
#******************************************************************************
  countdown_bagno:
    name: Countdown Bagno
    min: 0
    max: 7200
    step: 1
    initial: 1800
#------------------------------------------------------------------------------
input_boolean:
#------------------------------------------------------------------------------
  termostato_bagno_interruttore:
    name: Accendi
    initial: off
    icon: mdi:thermometer-lines
#******************************************************************************
  termostato_bagno_timer_interruttore:
    name: Timer
    initial: off
    icon: mdi:timer
#******************************************************************************
  countdown_bagno:
    name: Countdown Bagno
    initial: off
    icon: mdi:timelapse
#------------------------------------------------------------------------------
script:
#------------------------------------------------------------------------------
  scala_countdown_bagno:
    sequence:
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.countdown_bagno'
          value: "{{ states.sensor.countdown_bagno_meno_1.state | int }}"
      - service: script.turn_on
        data:
          entity_id: script.attendi_e_ripeti_countdown_bagno
#******************************************************************************
  attendi_e_ripeti_countdown_bagno:
    sequence:
      - condition: and
        conditions:
           - condition: state
             entity_id: input_boolean.countdown_bagno
             state: 'on'
           - condition: numeric_state
             entity_id: input_number.countdown_bagno
             above: '0'
      - delay:
          milliseconds: 9
      - service: script.turn_on
        data:
          entity_id: script.scala_countdown_bagno
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
  - alias: "Termostato Bagno Attiva Riscaldamento, basculante e limite massimo di 2 ore"
    trigger:
      platform: state
      entity_id: climate.termostato_bagno
      to: 'heat'
    action:
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.piu
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.basculante
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.timer
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.timer
      - delay:
            milliseconds: 100
      - service: switch.turn_on
        entity_id: switch.timer
#******************************************************************************
  - alias: "Termostato Bagno Accensione Manuale"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_interruttore
      to: 'on'
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: "climate.termostato_bagno"
          temperature: '{{ float(states.input_number.termostato_bagno_target_temp.state) }}'
#******************************************************************************
  - alias: "Termostato Bagno Spegnimento Manuale"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_interruttore
      to: 'off'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.termostato_bagno
          temperature: 0
#******************************************************************************
  - alias: "Termostato Bagno Regola Temperatura"
    trigger:
      platform: state
      entity_id: input_number.termostato_bagno_target_temp
    condition:
      - condition: state
        entity_id: input_boolean.termostato_bagno_interruttore
        state: 'on'
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: "climate.termostato_bagno"
          temperature: '{{ float(states.input_number.termostato_bagno_target_temp.state) }}'
#******************************************************************************
  - alias: "Termostato Bagno Spegni con timer"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_timer_interruttore
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.termostato_bagno_interruttore
      - delay: 'sensors.tempo_spegnimento_bagno'
      - service: homeassistant.turn_off
        entity_id: input_boolean.termostato_bagno_interruttore
      - service: homeassistant.turn_off
        entity_id: input_boolean.termostato_bagno_timer_interruttore
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.termostato_bagno_timer'
          value: "1800"
#******************************************************************************
  - alias: "Termostato Bagno disattiva timer in caso di spegnimento manuale"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_interruttore
      to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.termostato_bagno_timer_interruttore
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.termostato_bagno_timer'
          value: "1800"
#******************************************************************************
  - alias: 'Start Countdown'
    trigger:
      platform: numeric_state
      entity_id: input_number.countdown_bagno
      above: '0'
    condition:
      condition: state
      entity_id: input_boolean.countdown_bagno
      state: 'on'
    action:
      service: script.turn_on
      entity_id: script.scala_countdown_bagno
#******************************************************************************
  - alias: 'Start Countdown 2'
    trigger:
      platform: state
      entity_id: input_boolean.countdown_bagno
      to: 'on'
    condition:
      condition: numeric_state
      entity_id: input_number.countdown_bagno
      above: '0'
    action:
      service: script.turn_on
      entity_id: script.scala_countdown_bagno
#******************************************************************************
  - alias: 'Stop Countdown'
    trigger:
      platform: numeric_state
      entity_id: input_number.countdown_bagno
      below: '1'
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.countdown_bagno
#******************************************************************************
  - alias: 'Stop Countdown 2'
    trigger:
      platform: state
      entity_id: input_boolean.countdown_bagno
      to: 'off'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.countdown_bagno'
          value: "0"
      - service: homeassistant.turn_off
        entity_id: input_boolean.termostato_bagno_interruttore
      - service: homeassistant.turn_off
        entity_id: input_boolean.termostato_bagno_timer_interruttore
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.termostato_bagno_timer'
          value: "1800"
#******************************************************************************
  - alias: "Sincronizza Accensione countdown con accensione termostato"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_timer_interruttore
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.countdown_bagno
#******************************************************************************
  - alias: "Sincronizza Spegnimento countdown con spegnimento termostato"
    trigger:
      platform: state
      entity_id: input_boolean.termostato_bagno_timer_interruttore
      to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.countdown_bagno
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.termostato_bagno_timer'
          value: "1800"
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.countdown_bagno'
          value: "{{ ( ( states.input_number.termostato_bagno_timer.state | int) * 60 ) | int }}"
#******************************************************************************
  - alias: "Sincronizza tempo timer con countdown"
    trigger:
      platform: state
      entity_id: input_number.termostato_bagno_timer
    action:
      - service: input_number.set_value
        data_template:
          entity_id: 'input_number.countdown_bagno'
          value: "{{ ( ( states.input_number.termostato_bagno_timer.state | int) * 60 ) | int }}"
#******************************************************************************
